In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv('data.csv')

In [3]:
df.head()

      Name Gender    Count  Probability
0    James      M  5304407     0.014517
1     John      M  5260831     0.014398
2   Robert      M  4970386     0.013603
3  Michael      M  4579950     0.012534
4  William      M  4226608     0.011567

In [4]:
df = df[['Name', 'Gender']].copy()
df['Gender'] = df['Gender'].map({'M': 1, 'F': 0})
df['Gender'] = df['Gender'].astype(int)

In [5]:
df.head()

      Name  Gender
0    James       1
1     John       1
2   Robert       1
3  Michael       1
4  William       1

In [6]:
X = df
y = df["Gender"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 42, shuffle = True)

In [7]:
from Model_Naive_Bayes import GenderNaiveBayes

model = GenderNaiveBayes()
print("Training Model")
model.fit(X_train)
print("Training Complete")

Training Model
Training Complete

In [8]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report

print("prediction")

predictions_df = model.predict(X_test["Name"])
predictions_df.head()

prediction

   0
0  1
1  0
2  0
3  0
4  1

In [9]:
y_pred = predictions_df[0] 

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print(f"Accuracy:  {accuracy * 100:.2f}%")
print(f"Precision: {precision * 100:.2f}%")
print(f"Recall:    {recall * 100:.2f}%")
print(f"F1-Score:  {f1 * 100:.2f}%")

print("\n Classification Report")
print(classification_report(y_test, y_pred, target_names=["Female (0)", "Male (1)"]))

Accuracy:  76.56%
Precision: 67.81%
Recall:    75.32%
F1-Score:  71.37%

 Classification Report
              precision    recall  f1-score   support

  Female (0)       0.83      0.77      0.80     18029
    Male (1)       0.68      0.75      0.71     11425

    accuracy                           0.77     29454
   macro avg       0.75      0.76      0.76     29454
weighted avg       0.77      0.77      0.77     29454